export const mockProducts = [
  {
    artist: "Vincent_van_Gogh",
    date: 1887,
    description: "In 1886 Vincent...",
    fsid: 0,
    height: 493,
    id: 0,
    img: "/AIC.jpg",
    img_full: "https://www.artic.edu",
    link: "https://www.artic.edu",
    medium: "Oil on artist's board",
    place: "Paris",
    price: "$72,000,000",
    route: "vincent-van-gogh/self-portrait",
    stock: 60,
    title: "Self-Portrait",
    width: 388,
    shortDesc: "In 1886 Vincent...",
    test: true,
  },
  {
    artist: "Leonardo da Vinci",
    date: 1503,
    description: "Mona Lisa is a famous portrait...",
    fsid: 1,
    height: 770,
    id: 1,
    img: "/AIC.jpg",
    img_full: "https://www.artic.edu",
    link: "https://www.artic.edu",
    medium: "Oil on poplar wood",
    place: "Florence",
    price: "$860,000,000",
    route: "leonardo-da-vinci/mona-lisa",
    stock: 45,
    title: "Mona Lisa",
    width: 530,
    shortDesc: "Mona Lisa is a famous portrait...",
    test: true,
  },
  {
    artist: "Pablo Picasso",
    date: 1937,
    description: "Guernica is a powerful anti-war mural...",
    fsid: 2,
    height: 349,
    id: 2,
    img: "/AIC.jpg",
    img_full: "https://www.artic.edu",
    link: "https://www.artic.edu",
    medium: "Oil on canvas",
    place: "Paris",
    price: "$200,000,000",
    route: "pablo-picasso/guernica",
    stock: 30,
    title: "Guernica",
    width: 776,
    shortDesc: "Guernica is a powerful anti-war mural...",
    test: true,
  },
];
