export const mockProductContext = {
  cart: [
    {
      id: 0,
      title: "Self-Portrait",
      img: "/AIC.jpg",
      link: "https://www.artic.edu",
      description: "In 1886 Vincent...",
      medium: "Oil on artist's board",
      artist: "Vincent van Gogh",
      quantity: 1,
      price: "$72,000,000",
      route: "vincent-van-gogh/self-portrait",
      fsid: 0,
      stock: 1,
      width: 388,
      height: 388,
    },
  ],
  products: [
    {
      artist: "Vincent van Gogh",
      date: 1887,
      description: "In 1886 Vincent...",
      fsid: 0,
      height: 493,
      id: 0,
      img: "/AIC.jpg",
      img_full: "https://www.artic.edu",
      link: "https://www.artic.edu",
      medium: "Oil on artist's board",
      place: "Paris",
      price: "$72,000,000",
      route: "vincent-van-gogh/self-portrait",
      stock: 1,
      title: "Self-Portrait",
      width: 388,
      height: 388,
    },
  ],
  total: 72000000,
  numberOfItems: 1,
  addToCart: jest.fn(),
  removeFromCart: jest.fn(),
  checkout: jest.fn(),
  loaderProp: jest.fn(),
};
